all:
	g++ fs.cc -o fs libfs_server.a -w -pthread -ldl -std=c++11

test0:
	g++ test0.cc -o test0 libfs_client.a -w -std=c++11

test1:
	g++ test1.cc -o test1 libfs_client.a -w -std=c++11

test2:
	g++ test2.cc -o test2 libfs_client.a -w -std=c++11

test3:
	g++ test3.cc -o test3 libfs_client.a -w -std=c++11

test4:
	g++ test4.cc -o test4 libfs_client.a -w -std=c++11

test5:
	g++ test5.cc -o test5 libfs_client.a -w -std=c++11

test6:
	g++ test6.cc -o test6 libfs_client.a -w -std=c++11

test7:
	g++ test7.cc -o test7 libfs_client.a -w -std=c++11

test8:
	g++ test8.cc -o test8 libfs_client.a -w -std=c++11

test9:
	g++ test9.cc -o test9 libfs_client.a -w -std=c++11

test10:
	g++ test10.cc -o test10 libfs_client.a -w -std=c++11

test11:
	g++ test11.cc -o test11 libfs_client.a -w -std=c++11

test12:
	g++ test12.cc -o test12 libfs_client.a -w -std=c++11

test13:
	g++ test13.cc -o test13 libfs_client.a -w -std=c++11

test14:
	g++ test14.cc -o test14 libfs_client.a -w -std=c++11

test15:
	g++ test15.cc -o test15 libfs_client.a -w -std=c++11

test16:
	g++ test16.cc -o test16 libfs_client.a -w -std=c++11

test17:
	g++ test17.cc -o test17 libfs_client.a -w -std=c++11

test18:
	g++ test18.cc -o test18 libfs_client.a -w -std=c++11

test19:
	g++ test19.cc -o test19 libfs_client.a -w -std=c++11

clean:
	rm fs test0 test1 test2 test3 test4 test5 test6 test7 test8 test9 test10 test11 test12 test13 test14 test15 test16 test17 test18 test19

